//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class RomeDBEntities : DbContext
{
    public RomeDBEntities()
        : base("name=RomeDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<AccountCode> AccountCodes { get; set; }
    public DbSet<BillingProfile> BillingProfiles { get; set; }
    public DbSet<BillingProfileAccCode> BillingProfileAccCodes { get; set; }
    public DbSet<ClusterAccount> ClusterAccounts { get; set; }
    public DbSet<sParam> sParams { get; set; }
    public DbSet<TaxAuthority> TaxAuthorities { get; set; }
}
